{% set version = "2023.5" %}

package:
  name: gromacs_mpi
  version: {{ version }}

build:
  number: 0

source:
  url: http://ftp.gromacs.org/pub/gromacs/gromacs-{{ version }}.tar.gz

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >3.13
    - python >3.5
    - perl
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - libhwloc 2.*
    - fftw
    - plumed_mpi
    - mpich
  run:
    - fftw
    - libhwloc 2.*
    - plumed_mpi
    - mpich

test:
  commands:
    - gmx_mpi -version

about:
  home: http://www.gromacs.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GROMACS is a versatile package to perform molecular dynamics.

