{% set version = "2.9.0" %}

package:
  name: plumed_mpi
  version: {{ version }}

source:
  url: https://github.com/plumed/plumed2/archive/v{{ version }}.tar.gz

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - make
    - vim
  host:
    - fftw
    - gsl
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - zlib
    - mpich
  run:
    - gsl
    - gawk
    - llvm-openmp  # [osx]
    - fftw
    - mpich

test:
  commands:
    - plumed info --root
    - plumed info --long-version
    - plumed-patch -h
      #- plumed config has external_blas external_lapack gsl xdrfile zlib
      #- $PREFIX/lib/plumed/plumed-runtime -h
      #- test -f $PREFIX/lib/libplumed$SHLIB_EXT
      #- test -f $PREFIX/lib/libplumedWrapper.a
      #- test -f $PREFIX/lib/libplumedKernel$SHLIB_EXT
      #- conda inspect linkages -p $PREFIX $PKG_NAME
      #- conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.plumed.org/
  license: LGPL-3.0
  license_family: GPL
  license_file: COPYING.LESSER
  summary: 'Free energy calculations in molecular systems'
  description: |
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://www.plumed.org/doc
  dev_url: https://github.com/plumed/plumed2
